/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "SSD_config.h"
#include "SSD_interface.h"

u8 Globle_readKPDValue;

//void Delay(u32 copy_u32Time)
/*{
  for(u32 i=0;i<copy_u32Time;i++)
  {
	  for(u32 j=0;j<565;j++)
	  {
		  asm("NOP");
	  }
  }
}*/


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_voidInit();
	CLCD_voidInit();//LCD
	RCC_voidEnablePeripheralClock(RCC_APB2, RCC_GPIOA_ID);
	DIO_voidSetPinDirection(DIO_U8_PORTB, DIO_U8_PIN6, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPinDirection(DIO_U8_PORTB, DIO_U8_PIN7, DIO_OUTPUT_2MHZ_PP);
	DIO_voidSetPortDirection(DIO_U8_PORTA,DIO_OUTPUT_2MHZ_PP);
	//DIO_voidSetPortDirection(DIO_U8_PORTB,DIO_OUTPUT_2MHZ_PP);
	//DIO_u8SetPortValue(DIO_U8_PORTC, DIO_U8_LOW);
	/* Loop forever */
	while(1)
	{
        u8 i=0,j=0;
		//for(k=0;k<100;k++)
		//{}//_delay_ms(10);};
		DIO_voidSetPinValue(DIO_U8_PORTB, DIO_U8_PIN6, DIO_U8_HIGH);
		//SET_BIT(PORTB,6);
		DIO_voidSetPinValue(DIO_U8_PORTB, DIO_U8_PIN7, DIO_U8_LOW);
		//CLR_BIT(PORTB,7);
		SSD_voidSetNumber ( DIO_U8_PORTA, COM_CATODE,i);
		Delay(10);
		DIO_voidSetPinValue(DIO_U8_PORTB, DIO_U8_PIN7, DIO_U8_HIGH);
		//SET_BIT(PORTB,7);
		DIO_voidSetPinValue(DIO_U8_PORTB, DIO_U8_PIN6, DIO_U8_LOW);
		//CLR_BIT(PORTB,6);
		SSD_voidSetNumber ( DIO_U8_PORTA, COM_CATODE,j);
		Delay(10);

		if (i!=9)
		{
			i++;
		}
		else
		{
			i=0;
			if (j!=9)
			{
				j++;
			}

			else
				j=0;
		}

/**************************  end 7segment  *************************/

	Globle_readKPDValue=KPD_u8GetPressedkey();  //keypad

/**********************************************************************/

	CLCD_voidSendString('Nouran'); // LCD

/***************************************************************************/

	}
}

